package org.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-760026-redhat-00001
 * 2020-09-18T11:22:38.456+05:30
 * Generated source version: 3.2.7.fuse-760026-redhat-00001
 *
 */
@WebService(targetNamespace = "http://test.org/", name = "TestRequestSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TestRequestSoap {

    @WebMethod(operationName = "SampleRequest", action = "http://test.org/SampleRequest")
    @RequestWrapper(localName = "SampleRequest", targetNamespace = "http://test.org/", className = "org.test.SampleRequest")
    @ResponseWrapper(localName = "SampleRequestResponse", targetNamespace = "http://test.org/", className = "org.test.SampleRequestResponse")
    public void sampleRequest(
        @WebParam(name = "Number1", targetNamespace = "http://test.org/")
        int number1,
        @WebParam(name = "string2", targetNamespace = "http://test.org/")
        java.lang.String string2,
        @WebParam(mode = WebParam.Mode.INOUT, name = "string3", targetNamespace = "http://test.org/")
        javax.xml.ws.Holder<java.lang.String> string3,
        @WebParam(mode = WebParam.Mode.OUT, name = "SampleRequestResult", targetNamespace = "http://test.org/")
        javax.xml.ws.Holder<java.lang.Boolean> sampleRequestResult
    );
}
