package org.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-760026-redhat-00001
  * 2020-09-18T11:22:38.477+05:30
 * Generated source version: 3.2.7.fuse-760026-redhat-00001
 *
 */
@WebServiceClient(name = "TestRequest",
                  wsdlLocation = "http://0.0.0.0:8080/report?wsdl",
                  targetNamespace = "http://test.org/")
public class TestRequest extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.org/", "TestRequest");
    public final static QName TestRequestSoap = new QName("http://test.org/", "TestRequestSoap");
    public final static QName TestRequestSoap12 = new QName("http://test.org/", "TestRequestSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://0.0.0.0:8080/report?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestRequest.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://0.0.0.0:8080/report?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestRequest(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestRequest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestRequest() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap")
    public TestRequestSoap getTestRequestSoap() {
        return super.getPort(TestRequestSoap, TestRequestSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap")
    public TestRequestSoap getTestRequestSoap(WebServiceFeature... features) {
        return super.getPort(TestRequestSoap, TestRequestSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap12")
    public TestRequestSoap getTestRequestSoap12() {
        return super.getPort(TestRequestSoap12, TestRequestSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap12")
    public TestRequestSoap getTestRequestSoap12(WebServiceFeature... features) {
        return super.getPort(TestRequestSoap12, TestRequestSoap.class, features);
    }

}
